=  Longest Repeating Character Replacement

Given a string s that consists of only uppercase English letters, you can perform at most k operations on that string.
In one operation, you can choose any character of the string and change it to any other uppercase English character.
Find the length of the longest sub-string containing all repeating letters you can get after performing the above operations.

Note:
Both the string's length and k will not exceed 104.

Example 1:

Input:
s = "ABAB", k = 2

Output:
4

Explanation:
Replace the two 'A's with two 'B's or vice versa.

Description: https://leetcode.com/problems/longest-repeating-character-replacement/

== Naive solution, Brute force

We scan the array from the index 0 to right until the characters 


== Solution, Sliding Windos

We scan the array with a sliding window, which can expand right or shrink left. 

We use a data structure to count the occurrences of the 26 characters in the current window

We use an array of 26 integers to count the characters in the current window

Initially, the sliding window expands to the right, until we reach the limit of `k` operations
Then, we start moving the left side of the window.






----
characterReplacement( s, k)
	chars = s.chars
	int l=0, r=chars.len-1
	int 
	while( l<r )
	
	for int i=0 to nums.len-1
		if nums[i] > nums[i+1]
			return nums[i]
		return nums[0]
----

Time: O(n)

== Impl

See implementation in link:Solution.java[Java]

== References

* https://levelup.gitconnected.com/an-introduction-to-sliding-window-algorithms-5533c4fe1cc7[An Introduction to Sliding Window Algorithms]
