= CJ2020 Qual P3 - Parenting Partnering Returns

You are given a set of intervals representing the activities to be done by a kid.
The parents `C` and `J` need to assist the kid, so the activities are to be split.  
Split the activities in two non-overlapping sets for the parents `C` and `J`.

Examples

For instance, 
with intervals are `[360 480], [420 540], and [600 660]`, 
a valid non-overlapping splitting is `CJC`

Another example, 
With intervals `[99 150], [1 100], [100 301], [2 5], [150 250]`, 
a valid non-overlapping splitting is `JCCJJ`

== Solution - Interval partitioning (greedy)

Initially, we sort the activities by starting time, and we iterate through the list. 
We first assign activities to the parent who is not assigned any activity.
If both `C` and `J` are already assigned an activity, we pick the one whose activity ends first.
In case there is overlapping during the assignment, the partitioning is not possible.

----
Activity [] activities = sort_by_start( activities )
int end_C = 0, end_J = 0
String sequence = ""

for act in activities
	if end_C <= act.start
		end_C = act.end
		sequence.add( 'C' )
	else if end_J <= act.start
		end_J = act.end
		sequence.add( 'J' )
	else 
		return "IMPOSSIBLE"
return sequence
----



== Impl

See my implementation in link:Solution.java[Java]

See also

* https://codingcompetitions.withgoogle.com/codejam/submissions/000000000019fd27/eGlhb3d1YzE[xiaowuc1] #1 in c++
* https://codingcompetitions.withgoogle.com/codejam/submissions/000000000019fd27/c2FtLnJlaW5laHI[sam.reinehr] #17 in Java
* https://codingcompetitions.withgoogle.com/codejam/submissions/000000000019fd27/a21vZA[kmod] #20 in python 2
* https://codingcompetitions.withgoogle.com/codejam/submissions/000000000019fd27/amVycnltYW8[jerrymao] #25 in python 3 and c++
* https://codingcompetitions.withgoogle.com/codejam/submissions/000000000019fd27/cHpm[pzf] #29 in python3


== References

* https://www.cs.princeton.edu/~wayne/kleinberg-tardos/pearson/04GreedyAlgorithms-2x2.pdf[Chap 4.4 Interval Scheduling - cs Princeton]
