= Kickstart 2020 RC P2 - Stable Wall

A 2D array represents a wall made of sets of bricks of different shapes called polynomios.
A wall is stable if it can be built by adding polynomios sequentially, such that each polynomio is always supported.

Given a set of walls, determine if they are stable. If so, return an order in which you can build the wall. Otherwise, return "-1".

For example, the wall below is stable, and it can be built by adding, in order, the polynomios: `Z, O, A, M` 

----
ZOAAMM
ZOAOMM
ZOOOOM
ZZZZOM
----


Description: https://codingcompetitions.withgoogle.com/kickstart/round/000000000019ff43/00000000003379bb


== Solution

Idea: we scan the wall by column and we build a graph representing the polynomios and their chain of supports.
Id the graph has cycles, the wall is unstable. Otherwise, the building order corresponds to the graph's topological order. 

For instance, from the all in the example, build a directed graph with '`Z, O, A, M` vertices and `O -> Z`, `A -> O` edges.
The corresponding graph has no cycles, and a possible topological order is `Z, O, A, M`

Algorithm

----
solve( char[][] wall )

	graph = map<char, set<char>>
	rlen = wall.len
	clen = wall[0].len
	for r=0 to rlen-1
		for c=0 to clen-1
			curr = wall[r][c]
			if map[ curr ] == null
				map[ curr ] = new set<char>
			if( r+1 < rlen && curr != wall[r+1][c])
				map[curr].add( wall[r+1][c] )
	if has_cycle(graph)
		return "-1"
	return topological_order(graph)
----

We detect cycles in the graph by running a DFS on all nodes and checking if any node is being visited twice within the same recursion stack.

----
has_cycle(graph)
	marked=[]
	visited=[]
	for node in graph
		if has_cycle(node, marked, visited)
			return true
	return false

has_cycle(node, marked, visited)
	marked[node] = true
	for child in node.adjacent
		if marked[child]
			return true // cycle detected
		else if !visited[child] && hash_cycle(child, marked, visited)
			return true;		
	return false
----

If not acyclic, we have a DAG, hence we can compute the topological order by running a reverse post-order DFS traversal. 




== Impl

See my implementation in link:Solution.java[Java]

See other's implementation

* C++:
https://codingcompetitions.withgoogle.com/kickstart/submissions/000000000019ff43/dG13aWxsaWFtbGluMTY4[tmwilliamlin168] (#1), 
https://codingcompetitions.withgoogle.com/kickstart/submissions/000000000019ff43/RXJyaWNodG8[errichto] (#3) 
https://codingcompetitions.withgoogle.com/kickstart/submissions/000000000019ff43/SGVsdGlvbg[Heltion] (#4) 
* Java: 
https://codingcompetitions.withgoogle.com/kickstart/submissions/000000000019ff43/ZWF0bW9yZQ[eatmore] (#2),
https://codingcompetitions.withgoogle.com/kickstart/submissions/000000000019ff43/a2hva2hhcm5pa3Vuajg[khokharnikunj8] (#36),
https://codingcompetitions.withgoogle.com/kickstart/submissions/000000000019ff43/SmVlbF9WYWlzaG5hdg[Jeel_Vaishnav] (#42)
* Python 3: 
https://codingcompetitions.withgoogle.com/kickstart/submissions/000000000019ff43/ei5zaGk[z.shi] (#27)

