= CJ2020 R1C P1 - Overexcited Fan

A celebrity is moving in a 2D discrete world. It starts from (x,y) and for each time unit moves in one of the four cardinal direction. Its path is given in form "NSSWEEE...". You start from (0,0) and for each time unit, you can move one block or stay still.

Determine if you can reach the celebrity along its path and, if so, which is the minimum time you need .

Description: https://codingcompetitions.withgoogle.com/codejam/round/000000000019fef4/0000000000317409[CodeJam 20, round 1C, Problem 1]


== Solution - Manhattan Distance (L1 Distance)

The idea is to simulate the celebrity path, and then, for each step Si determine if you can reach the point in time, starting from your position. If so max(your-time-to-Si, celeb-time-to-Si) is a possible way to reach the celebrity. To complete problem, you need to select the minimum of the above distances. 

----
int result = MAX_INT
char[] steps = "NSWEEE".chars
int[][] tour = new int[steps.len+1][2]
tour[0] = {X, Y}
// calculate all steps
for int i=0 to tour.len-2
    tour[i+1] = computeMove(tour[i], steps[i])
// simulate path, from end to start
for int i=tour.len-1 to 1
    int pos[] = tour[i]
    // you start from (0,0)
    int l1dist = abs(pos[0]) + abs(pos[1])
    if( l1dist < i)
        time = max( l1dist, i)
        result = min(result, time)
return result;
----


== Impl

See implementation in link:Solution.java[Java]

