#!/bin/bash

run(){
    run_java(){
        java -cp ../../../../bin/ lc.s1.p00.Solution < in.txt
    }
    run_py(){
        python3 Solution.py < in.txt
    }
    usage(){
        echo "usage: run  -j | -p  [ -x ]"
    }
    while [ "$1" != "" ]; do
        case $1 in
            -j | --java8 )      run_cmd=run_java ;;
            -p | --python3 )    run_cmd=run_py ;;
            -h | --help )       usage; exit ;;
            * )                 usage; exit 1
        esac
        shift
    done
}

run "${@}"
